### ISSUE TITLE
PINE64 and their LoRaWAN hybrid mesh utilizing NDN

### ISSUE THREAD

**Issue by dumblob** [named-data/NDN-packet-spec#4]
The company PINE64 (I hope I don't need to introduce this highly influential company) made a [huge decision](https://www.pine64.org/2021/02/15/february-update-show-and-tell/ ) few weeks ago. After years of strategically analyzing different wireless mesh-like technologies with wide range capabilities, they decided for LoRa (LoRaWAN). They'll integrate LoRaWAN with **all** their products (smartphones, tablets, SBCs, notebooks, etc.) will have this technology integrated (both HW & SW wise).

They'll need a solid future-proof decentralized network technology to make it happen.

Could you contact them and tell them something about NDN to find synergies how to collaborate? Could your NDN organization discuss this at a higher managerial level?

**Comment by yoursunny** [comment]
The current NDN protocol works on **LoRa**. My [esp8266ndn](https://github.com/yoursunny/esp8266ndn) library used to have an implementation, although it's absent in current version.
**LoRaWAN**, on the other hand, is a point-to-point protocol between endnode and gateway. It is fundamentally incompatible with NDN: you would have to actively fight against it to get NDN working.

In either case, this is not a spec issue.
You may join [ndn-interest](https://www.lists.cs.ucla.edu/mailman/listinfo/ndn-interest) mailing list for further discussion.

**Comment by dumblob** [comment]
Thanks for a quick reply!

The main point of my request was to contact PINE64 as they'll be glad if the did not need to depend on the current internet architecture (in the blog post I linked, they want to interface with the current internet, but they plan to build a decentralized "parallel" network - therefore both LoRa and LoRaWAN).

Would your management approve approaching PINE64?

**Comment by yoursunny** [comment]
This is not a spec issue. Please ask on ndn-interes mailing list.
https://www.lists.cs.ucla.edu/mailman/listinfo/ndn-interest
